mounts:
  - source: node_modules/@hyas/core/assets
    target: assets
  - source: node_modules/@hyas/core/layouts
    target: layouts
  - source: node_modules/gethyas/assets
    target: assets
  - source: node_modules/gethyas/static
    target: static
  - source: node_modules/bootstrap/scss
    target: assets/scss/bootstrap
  - source: node_modules/@hyas/bootstrap/layouts
    target: layouts
  - source: node_modules/flatpickr/dist
    target: assets/flatpickr
  - source: node_modules/vuetify/dist/vuetify.min.js
    target: assets/js/vendor/vuetify.min.js
  - source: node_modules/vuetify/dist/vuetify.min.css
    target: assets/css/vendor/vuetify.min.css
  - source: node_modules/netlify-identity-widget/build/netlify-identity-widget.js
    target: assets/js/vendor/netlify-identity-widget.js
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: static
    target: static
  - source: Example Site/content
    target: content


  