title: Cookbook
titleSeparator: '-'
titleAddition: Des recettes pour pleins
description: Site collaboratif de partage de recettes et d'organisation d'évènement pour les cantines autogérées.
images:
  - cover.png
ogLocale: fr
titleHome: Cookbook
schemaType: Organization
schemaName: Cookbook
schemaAuthor: encas-parka
schemaAuthorGitHub: https://github.com/encas-parka
schemaLocale: fr-FR
schemaLogo: logo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: cover.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: ""
schemaLinkedIn: ""
schemaGitHub: ""
themeColor: '#fff'
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
defaultImage: cover.png
fillImage: 1280x720 Center
footer: Powered by <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, and <a href="https://gethyas.com/">Hyas</a>
copyRight: ""
alert: false
alertDismissable: true
alertText: Deliver web projects 10x faster. <a class="alert-link" href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get the free enterprise paper →</a>
seo:
  - title:
    separator: " | "
    suffix: "Cookbook"
  - favicons:
    icon: "favicon.png"
    svgIcon: "favicon.svg"