name = "hugo-enka-cookbook"
license = "GNU General Public"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.html"
description = "Hugo theme for recipes based on Hyas theme"
homepage = "https://github.com/encas-parka/hugo-enka-cookbook"
tags = ["modern", "bootstrap", "cookbook", "vuejs" ]
features = ["seo-ready", "development tools", "bootstrap framework", "netlify-ready", "decap-cms"]

[author]
  name = "QaldeK"

