name = "hugo-enka-cookbook"
license = "GNU General Public"
licenselink = ""
description = "Hugo theme for recipes based on Hyas "
homepage = ""
tags = ["landing page", "blog", "minimal", "modern", "customizable", "bootstrap", "recipe"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "netlify-cms"]
min_version = "0.75.0"

[author]
  name = "QaldeK"
  homepage = ""
