mounts:
  - source: exampleSite/content
    target: content

  - source: exampleSite/data
    target: data

  - source: content
    target: content

  - source: data
    target: data

  - source: static
    target: static

  - source: assets
    target: assets