
mounts:
# bootstrap
  - source: node_modules/bootstrap/scss
    target: assets/scss/bootstrap
  - source: node_modules/bootstrap/dist/js/bootstrap.bundle.js
    target: assets/js/bootstrap.js

# flatpickr
  - source: node_modules/flatpickr/dist/
    target: assets/flatpickr

# vuejs2
  - source: node_modules/vue/dist/vue.min.js
    target: assets/js/vendor/vue.min.js  
  - source: node_modules/vue/dist/vue.js
    target: assets/js/vendor/vue.js

# vuetify
  - source: node_modules/vuetify/dist/vuetify.js
    target: assets/js/vendor/vuetify.js
  - source: node_modules/vuetify/dist/vuetify.min.css
    target: assets/css/vendor/vuetify.min.css

# netlify-identity-widget
  - source: node_modules/netlify-identity-widget/build/netlify-identity-widget.js
    target: assets/js/vendor/netlify-identity-widget.js

# local : pour prédominance des fichier locaux
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: static
    target: static

# exampleSite
  - source: exampleSite/content
    target: content

  